### ISSUE TITLE
Any idea how to change the starting position to the Good arc?

### ISSUE THREAD

**Issue by willvlad** [Mindinventory/Flutter-review-page-interaction#2]
Nice widget, but from the code it's not very easy to figure out how to change the starting position to the "Good" rather than "Ok" arc? Any suggestions?

**Comment by xyzvoyager** [comment]
> Nice widget, but from the code it's not very easy to figure out how to change the starting position to the "Good" rather than "Ok" arc? Any suggestions?

It's just coming from an array of items, Did you just try changing it's sequence of adding to arcItems?
